name: Run Playwright Tests 🎭

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: # Позволяет запускать тесты вручную одной кнопкой в интерфейсе GitHub

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' # Идеальная стабильная версия для QA-стека
        cache: 'pip'

    - name: Install dependencies via pip-tools
      run: |
        python -m pip install --upgrade pip
        pip install pip-tools
        # Компилируем чистый requirements.txt прямо в CI, гарантируя отсутствие конфликтов
        pip-compile requirements\requirements.in
        pip install -r requirements\requirements.txt

    - name: Ensure Playwright browsers are installed
      run: |
        playwright install --with-deps chromium

    - name: Run UI tests with Pytest
      run: |
        # Запускаем в headless-режиме (без отображения окна), результаты пишем в allure-results
        pytest --alluredir=allure-results
      continue-on-error: true # Позволяет продолжить сборку отчета, даже если тесты упали

    - name: Get Allure history
      uses: actions/checkout@v4
      if: always()
      with:
        ref: gh-pages
        path: gh-pages

    - name: Generate Allure Report
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
